DROP USER IF EXISTS ${user};

CREATE USER ${user} WITH ENCRYPTED PASSWORD '${password}';
GRANT CONNECT ON DATABASE ${db} TO ${user};
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO ${user};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${user};
